### ISSUE TITLE
`!mp start` command without args doesn't work?

### ISSUE THREAD

**Issue by Lekuruu** [osuTitanic/anchor#70]
I've noticed while testing, that the `!mp start` command doesn't work when not providing any arguments.
The client will just kinda... uhh... exit out of the match and teleport back to the menu, with the text `There was an error while loading this beatmap...`.

**Comment by Lekuruu** [comment]
Seems to be an issue with the client...?

Here is the stacktrace:
```
System.NullReferenceException:
   at osu.GameModes.Play.Components.Scoreboard.Add(ScoreboardEntry s)
   at osu.GameModes.Play.Components.Scoreboard.SetTrackingEntry(ScoreboardEntry tracking)
   at osu.GameModes.Play.TeamRulesets.MultiRuleset.PopulateScoreboard()
   at osu.GameModes.Play.PlayerVs.InitializeScoreboard()
   at osu.GameModes.Play.Player.OnLoadStart()
   at osu.GameModes.Play.PlayerVs.OnLoadStart()
   at osu.Graphics.ASyncLoader.run()
```

I will close this for now...
